planner:
  ros__parameters:
    plan_solver_plugins: ["UPF"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
    UPF:
      plugin: "plansys2/UPFPlanSolver"
      solver: "optic"